### ISSUE TITLE
thx to release and  i get this error

### ISSUE THREAD

**Issue by madlifer** [Clintoxen/PUBG-Afk-FarmBot#1]
> Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)] on win32
> Type "copyright", "credits" or "license()" for more information.
> >>> 
> ================ RESTART: C:\Users\Administrator\Desktop\a.py ================
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Desktop\a.py", line 8, in <module>
>     import psutil
> ModuleNotFoundError: No module named 'psutil'
> >>>

**Comment by Clintoxen** [comment]
I forgot to add the document that told you which requirements to install. Take a look at the requirements file I just uploaded and rum the commands in cmd
