### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by MatheusSw** [Clintoxen/PUBG-Afk-FarmBot#3]
```
threehundredws = []
for _ in range(300):
    threehundredws.append('w')
```
could be switched for `threehundredsws = [ 'w' * 300]`

**Comment by Karriff** [comment]
https://www.virustotal.com/#/file/591fbb6ae3c405a376783bb8d1c673beb9b5c3fd638a7aa89a6cdaf617deea6c/detection

**Comment by Clintoxen** [comment]
Ill take a look at this again later when I have more than an hour of sleep

**Comment by Clintoxen** [comment]
I just updated the source with my current build, let me know if that addresses this @MatheusSw
