### ISSUE TITLE
Bot not working.

### ISSUE THREAD

**Issue by sadow200** [Clintoxen/PUBG-Afk-FarmBot#5]
I start the bot and pick my res then hit start.
The game loads then just sits there doing nothing and the bot is not responding.

Using Full Screen(Windowed) RES:1920x1080

**Comment by Clintoxen** [comment]
Are you using reshade or anything else that can change the color of the game? @sadow200

**Comment by sadow200** [comment]
No just default game

**Comment by Clintoxen** [comment]
Hmm that usually means the bot is not recognizing the playstate, meaning it doesn know the game is open. Normally caused by  a program modifying the games colors like reshade or, nvidia control panel.  Is your monitor set to 1920 x 1080 as well or just the game?

**Comment by sadow200** [comment]
Yes my game and monitor are set the same and I even tried changing the game res and bot res still wouldn't work

**Comment by Clintoxen** [comment]
Yea I just tried it and it didnt work for me, its possible one of my last updates messed something up for that resolution since 1440p is working. Ill put out a new build if i can do it in the next 10 mins otherwise it will be tonight! Sorry about that

**Comment by Clintoxen** [comment]
Try the new release it should be working now https://github.com/Clintoxen/PUBG-Afk-FarmBot/releases/tag/1.05 @sadow200
