### ISSUE TITLE
bot keeps opening settings and wont quit

### ISSUE THREAD

**Issue by dustyroo** [Clintoxen/PUBG-Afk-FarmBot#6]
title said it all pretty much. size is 1080 and also when I hit esc and go to leave because it wont do and it clicks cancel.

**Comment by dustyroo** [comment]
tried to fix the issue by myself and got these errors.

`missing module named resource - imported by posix, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py
missing module named posix - imported by os, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py
missing module named _posixsubprocess - imported by subprocess, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py
missing module named org - imported by pickle, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py
missing module named readline - imported by cmd, code, pdb, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py
excluded module named _frozen_importlib - imported by importlib, importlib.abc, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py
missing module named _frozen_importlib_external - imported by importlib._bootstrap, importlib, importlib.abc, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py
missing module named _winreg - imported by platform, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py
missing module named _scproxy - imported by urllib.request
missing module named java - imported by platform, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py
missing module named 'java.lang' - imported by platform, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py, xml.sax._exceptions
missing module named vms_lib - imported by platform, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py
missing module named termios - imported by tty, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py, getpass
missing module named grp - imported by shutil, tarfile, pathlib, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py
missing module named pwd - imported by posixpath, shutil, tarfile, http.server, webbrowser, psutil, pathlib, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py, netrc, getpass
missing module named 'org.python' - imported by copy, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py, xml.sax
missing module named _dummy_threading - imported by dummy_threading, C:\Users\Dustyroo\Downloads\PUBG-Afk-FarmBot-master\AfkFarm.py
missing module named 'Xlib.XK' - imported by pyautogui._pyautogui_x11
missing module named 'Xlib.ext' - imported by pyautogui._pyautogui_x11
missing module named Xlib - imported by pyautogui._pyautogui_x11
missing module named AppKit - imported by pyautogui._pyautogui_osx
missing module named Quartz - imported by pyautogui._pyautogui_osx
missing module named PIL._imagingagg - imported by PIL, PIL.ImageDraw
missing module named numpy - imported by pyscreeze
missing module named cv2 - imported by pyscreeze
missing module named Tkinter - imported by pymsgbox, PIL.ImageTk
missing module named 'PySide.QtCore' - imported by PIL.ImageQt
missing module named 'PyQt4.QtCore' - imported by PIL.ImageQt
missing module named 'PyQt5.QtCore' - imported by PIL.ImageQt
missing module named pathlib2 - imported by PIL.Image
missing module named cffi - imported by PIL.Image, PIL.PyAccess, PIL.ImageTk
missing module named __builtin__ - imported by PIL.Image
missing module named psutil._psutil_aix - imported by psutil, psutil._psaix
missing module named psutil._psutil_sunos - imported by psutil, psutil._pssunos
missing module named psutil._psutil_bsd - imported by psutil, psutil._psbsd
missing module named psutil._psutil_osx - imported by psutil, psutil._psosx
missing module named _psutil_linux - imported by psutil
missing module named psutil._psutil_posix - imported by psutil, psutil._pslinux, psutil._psosx, psutil._psbsd, psutil._pssunos, psutil._psaix
`

**Comment by Traaka** [comment]
Same problem.

**Comment by Clintoxen** [comment]
Are you using the GUI bot? Or the old source code? 

But ill look into it in a little bit, I probably need to adjust the coordinates for the 1080p config

**Comment by Clintoxen** [comment]
And how far does the bot get before this happens? Do you get through the main menu, then lobby, then plane jump and then a few minutes it opens the menu?

**Comment by Traaka** [comment]
Im using the GUI, It gets through the main menu and jumps out the plane, waits a few minutes on the ground then opens up settings.

**Comment by dustyroo** [comment]
it does it when it wants to quit, fucking title mistake

**Comment by Clintoxen** [comment]
try this one https://github.com/Clintoxen/PUBG-Afk-FarmBot/releases/tag/1.06 @dustyroo @Traaka 

moved #2 here

**Comment by Traaka** [comment]
Just tried it. It opens the ESC menu and nothing happens.

**Comment by Clintoxen** [comment]
alright well give me like an hour and then I should have some more free time to reproduce this and fix it

**Comment by dustyroo** [comment]
Ok now it just opens the menu and nothing happens. also again when I click exit to lobby it clicks 'cancel' when it should click 'ok'

**Comment by Clintoxen** [comment]
It was my fault, i wasnt updating the right file, I repuloaded and it should work https://github.com/Clintoxen/PUBG-Afk-FarmBot/releases/download/1.06/AfkBot.1.06.1.zip

**Comment by Traaka** [comment]
Yeah now it works! Thanks. Will be testing it for a couple of matches ;)

**Comment by Clintoxen** [comment]
cool thanks for helping testing it you guys, sorry for the trouble
